# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taghound < Formula
  desc "A fast CLI tool that tracks Git releases by reading branches and tags"
  homepage "https://github.com/jee4nc/taghound"
  version "0.1.4"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jee4nc/taghound/releases/download/v0.1.4/taghound_darwin_amd64.tar.gz"
      sha256 "f54122caa00eb5805b6e05a558c4f8e8515a60e01e3b5d7f41dfb0e61af942e6"

      define_method(:install) do
        bin.install "taghound"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jee4nc/taghound/releases/download/v0.1.4/taghound_darwin_arm64.tar.gz"
      sha256 "dd1b126be7c8a19a032ef2b31f32741f52cb3c8f82e47b46acaceaa703170728"

      define_method(:install) do
        bin.install "taghound"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jee4nc/taghound/releases/download/v0.1.4/taghound_linux_amd64.tar.gz"
      sha256 "406909f1e28939c3ae227de2c629958d5ff839a8a9e9bed32182d8ed59950357"
      define_method(:install) do
        bin.install "taghound"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jee4nc/taghound/releases/download/v0.1.4/taghound_linux_arm64.tar.gz"
      sha256 "c0b69f1372127ddb2579fdc2bd8becffbdae39fb15f979afada6664e6b0c4660"
      define_method(:install) do
        bin.install "taghound"
      end
    end
  end

  test do
    system "#{bin}/taghound", "--version"
  end
end
