# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taghound < Formula
  desc "A fast CLI tool that tracks Git releases by reading branches and tags"
  homepage "https://github.com/jee4nc/taghound"
  version "0.1.2"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jee4nc/taghound/releases/download/v0.1.2/taghound_darwin_amd64.tar.gz"
      sha256 "06e75cdd0a02fd79d914d554c7b369e6a1bff8723edddc6a8335ec5e4225d084"

      define_method(:install) do
        bin.install "taghound"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jee4nc/taghound/releases/download/v0.1.2/taghound_darwin_arm64.tar.gz"
      sha256 "892c4cc69b8a6d77252c14e527ac3b6c50112470759fef941fb008272cbcec41"

      define_method(:install) do
        bin.install "taghound"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jee4nc/taghound/releases/download/v0.1.2/taghound_linux_amd64.tar.gz"
      sha256 "2a082acedc7e6148b6b72e965ac57304c5fbabac56d622b7bf754021526cb1f6"
      define_method(:install) do
        bin.install "taghound"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jee4nc/taghound/releases/download/v0.1.2/taghound_linux_arm64.tar.gz"
      sha256 "a25d9b2331b4fac6eae4ec1df5340a4e39b54fc5fb3118e7c12aa38532db2bc8"
      define_method(:install) do
        bin.install "taghound"
      end
    end
  end

  test do
    system "#{bin}/taghound", "--version"
  end
end
